command: ['chainlit', 'run', 'app.py']


env:
  - name: CHAINLIT_AUTH_SECRET
    value: "F8*9Z/LVfsoHzEt_/IvaI4s1-.1cd/bQ%Bmd5w5$FcXP$ga=taQR_,YE9Q91xnSG"

  # SERVING_ENDPOINT and DATABASE_INSTANCE are injected via databricks.yml
  # app config.env block. Override locally in .env for development.

  - name: ENABLE_HEADER_AUTH
    value: true

  - name: ENABLE_PASSWORD_AUTH
    value: false